# tinygrad relies on metal support
c_stdlib_version:   # [osx]
  - 15.5            # [osx]
MACOSX_SDK_VERSION: # [osx]
  - 15.5            # [osx]

github_actions_labels:          # [unix]
  - namespace-profile-8cpu-on-linux-64    # [linux]
  # This one below should be for GPU, but there's no GPU provider anymore/yet
  - namespace-profile-16cpu-on-linux-64   # [linux]
  - namespace-profile-12cpu-on-osx-arm64  # [osx]
