azure:
  free_disk_space: true
  settings_win:
    variables:
      CONDA_BLD_PATH: "C:\\bld\\"
      SET_PAGEFILE: 'True'
build_platform:
  linux_aarch64: linux_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_install_tool: pixi
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
github_actions:
  self_hosted: true
  triggers:
  - push
  - pull_request
provider:
  osx_arm64: github_actions
